name = "FlightMechanicsUtils"
uuid = "0ddfa1e6-9159-4d5a-8b9e-3a0591f1f4a7"
authors = ["Alex Saez <saezm.alex@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.0"
Documenter = "0.26"
julia = "1.5"
